# Generated by Django 4.2.14 on 2024-09-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvosApp', '0002_remove_orderitem_meal_orderitem_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='meal',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='meal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='EvosApp.meal'),
            preserve_default=False,
        ),
    ]
