# Generated by Django 4.2.14 on 2024-09-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvosApp', '0003_remove_orderitem_meal_orderitem_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
